ci:
  autoupdate_commit_msg: |
    [pre-commit.ci] pre-commit autoupdate [norelease]

exclude: ^migrations/ ^static/ ^node_modules/ ^e2e-tests/tests/\w.spec.ts

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--ignore-init-module-imports"
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus

  - repo: https://github.com/kplaube/pre-commit-dodgy
    rev: "0.0.2"
    hooks:
      - id: dodgy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - "--recursive"
          - "--in-place"
          - "--wrap-summaries=88"
          - "--wrap-descriptions=88"
          - "--pre-summary-newline"

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-requests==2.28.11.7"
        args:
          - "--ignore-missing-imports"
          - "--scripts-are-modules"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: consent_api/templates/
        types_or: ["javascript", "css"]

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.54.0
  #   hooks:
  #     - id: eslint
