"""
Empty message.

Revision ID: 18836f16960b
Revises:
Create Date: 2022-11-25 14:52:50.317857
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "18836f16960b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_consent",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("consent", postgresql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_consent")
    # ### end Alembic commands ###
