name: Deploy PR branch

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  issues: write
  checks: read
  id-token: write

jobs:

  deploy-request:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ steps.branch-deploy.outputs.environment }}
      url: ${{ steps.deploy.outputs.url }}

    env:
      IMAGE: gcr.io/${{ vars.GOOGLE_PROJECT }}/${{ vars.SERVICE_ID }}

    steps:
      - uses: github/branch-deploy@v4.3.0
        id: branch-deploy
        with:
          trigger: ".deploy"
          allow_forks: false
          environment: dev

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access-token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ format("{0}:{1}", env.IMAGE, steps.branch-deploy.outputs.ref) }}

      - uses: google-github-actions/deploy-cloudrun@v0
        id: deploy
        with:
          service: ${{ vars.SERVICE_ID }}
          region: ${{ vars.REGION }}
          image: ${{ env.IMAGE }}:${{ steps.branch-deploy.outputs.ref }}
