name: Deploy PR branch

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  issues: write
  checks: read
  id-token: write

jobs:

  request:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    outputs:
      continue: ${{ steps.branch-deploy.outputs.continue }}
      environment: ${{ steps.branch-deploy.outputs.environment }}
      noop: ${{ steps.branch-deploy.outputs.noop }}
      ref: ${{ steps.branch-deploy.outputs.ref }}

    steps:
      - uses: github/branch-deploy@v4.3.0
        id: branch-deploy
        with:
          trigger: ".deploy"
          allow_forks: false
          environment: development

  deploy:
    uses: alphagov/consent-api/.github/workflows/deploy.yaml@main
    needs: request
    with:
      image_name: ${{ vars.DOCKER_IMAGE }}
      tag: ${{ needs.request.outputs.ref }}
      is_branch: true
      environment: ${{ needs.request.outputs.environment }}
      noop: ${{ needs.request.outputs.noop == 'true' }}
    secrets: inherit
