name: Build and deploy

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      branch-or-tag:
        required: true
        type: string
      latest:
        required: false
        type: boolean
      service-id:
        required: true
        type: string
      region:
        required: false
        default: europe-west2
    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true
    outputs:
      url:
        description: "The deployment URL"
        value: ${{ jobs.build-and-deploy.outputs.url }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    outputs:
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-or-tag }}

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access-token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ inputs.latest && format("{0}:latest", inputs.image-name) }}
            ${{ format("{0}:{1}", inputs.image-name, inputs.branch-or-tag) }}

      - uses: google-github-actions/deploy-cloudrun@v0
        id: deploy
        with:
          service: ${{ inputs.service-id }}
          region: ${{ inputs.region }}
          image: ${{ format("{0}:{1}", inputs.image-name, inputs.branch-or-tag) }}
