name: Consent API CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  ENV: ci

jobs:

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Lint
      run: |
        make lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Run tests
      run: |
        make test-coverage

    - name: Report code coverage
      uses: codecov/codecov-action@v3

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
