name: Consent API CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  ENV: ci

jobs:

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Lint
      run: |
        make lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Run tests
      run: |
        make test-coverage

    - name: Report code coverage
      uses: codecov/codecov-action@v3
