name: Consent API CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  FLASK_APP: consent_api
  ENV: ci

jobs:

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Lint
      run: |
        make lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install dependencies
      run: |
        make deps

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: |
        make run-migrations
        make test-coverage

  deploy:
    name: Tag and trigger deployment
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Bump version and push tag
      uses: rymndhng/release-on-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump_version_scheme: minor
        use_github_release_notes: true
