name: Consent API CI

on:
  push:
    branches: [ $default-branch ]
  pull-request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:

  lint:
    name: "Lint and static checks"
    runs-on: ubuntu-latest

    env:
      ENV: ci

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version-file: ".python-version"
        cache: "pip"

    - name: Install dependencies
      run: |
        make deps

    - name: Run linter
      run: |
        make lint

  test:
    name: "Run tests"
    runs-on: ubuntu-latest

    env:
      ENV: ci

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version-file: ".python-version"
        cache: "pip"

    - name: Install dependencies
      run: |
        make deps

    - name: Run tests
      run: |
        make test-coverage

    - name: Report code coverage
      uses: codecov/codecov-action@v3

  # docker-image:
  #   name: "Build Docker image"
  #   runs-on: ubuntu-latest

  #   env:
  #   - name: Build Docker image
  #     run: |
  #       make docker-image

  #   - name: Push Docker image
  #     run: |
  #       make docker-push
