name: Deploy main branch

on:
  push:
    branches: ['main']

permissions:
  contents: write
  id-token: write

jobs:

  release:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      id: release
      uses: rymndhng/release-on-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump_version_scheme: patch
        use_github_release_notes: true

  deploy:
    uses: alphagov/consent-api/.github/workflows/deploy.yaml@main
    needs: release
    if: needs.release.outputs.tag_name != ''
    with:
      google_project: ${{ vars.GOOGLE_PROJECT }}
      service: ${{ vars.SERVICE_ID }}
      region: ${{ vars.REGION }}
      image_name: ${{ vars.SERVICE_ID }}
      tag: ${{ needs.release.outputs.tag_name }}
      environment: staging

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: pip

    - run: make deps

    - run: make test-e2e
      env:
        SELENIUM_DRIVER: remote
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        E2E_TEST_CONSENT_API_URL: ${{ needs.deploy.outputs.url }}
        E2E_TEST_GOVUK_URL: https://sde-prototype-govuk-j4f7bdslta-nw.a.run.app/
        E2E_TEST_HAAS_URL: https://haas-j4f7bdslta-nw.a.run.app/
