name: Merge PR branch to main

on:
  push:
    branches: ['main']

jobs:

  release:
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: write
      id-token: write

    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-staging:
    uses: alphagov/consent-api/.github/workflows/deploy.yaml@main
    needs: release
    if: needs.release.outputs.tag_name != ''
    with:
      image_name: ${{ vars.DOCKER_IMAGE }}
      tag: ${{ needs.release.outputs.tag_name }}
    secrets: inherit
    permissions:
      contents: write
      id-token: write

  smoke-test:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Smoke tests"

  load-tests:
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Load tests"
