name: Test branch

on: [pull_request]

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}:${{ github.head_ref }}
      CHROME_VERSION: "110.0"
      SPLINTER_REMOTE_BROWSER_VERSION: "110.0"

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v4
        name: Build image
        with:
          load: true
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: docker pull selenoid/chrome:${{ env.CHROME_VERSION }}

      - run: make test-end-to-end-docker
        name: Run tests

      - uses: docker/build-push-action@v4
        name: Push image
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
