name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: true
        default: "latest"

jobs:
  deploy-to-production:
    uses: alphagov/consent-api/.github/workflows/deploy.yaml@main
    with:
      image_name: ${{ vars.DOCKER_IMAGE }}
      image_tag: ${{ inputs.tag }}
      environment: "production"
    secrets: inherit
    permissions:
      contents: write
      id-token: write

  smoke-test:
    needs: deploy-to-production
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Smoke tests agains production"

  load-tests:
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Load tests against production"
